# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true

# Setup
title:               seekorswim
tagline:             'My Security Blog'
description:         'A personal blog for documenting my research and learning in various aspects of computer security.'
url:                 https://seekorswim.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Larry Brown
  url:               https://twitter.com/seekorswim633
  email:             seekorswim [@] seekorswim [dot] net

# Custom vars
version:             1.0.0
